version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: eration
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eration_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
